"""Document list with virtual collection, keyboard navigation, and bulk selection"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/document_list.ipynb.

# %% auto #0
__all__ = ['build_document_columns', 'create_document_cell_renderer', 'render_toolbar', 'render_list_scripts',
           'render_document_list']

# %% ../../nbs/components/document_list.ipynb #2350c61c
from typing import Any, Callable, List, Set

from fasthtml.common import (
    Div, Span, A, Button, Input, Label, Script
)

# DaisyUI components
# btn / btn_styles / btn_colors / btn_sizes still used by render_icon_button
# (helper, V1 catalog gap) and the inline `<A>` Export anchor in the cell
# renderer. Other sites in this file use V1 buttons directly.
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_styles, btn_sizes
)
from cjm_fasthtml_daisyui.components.data_input.checkbox import (
    checkbox, checkbox_sizes
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

from cjm_fasthtml_design_system.text_tiers import text_tiers

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, min_h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V1 button roles, V11 icon-size roles)
from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons

# App core: V12 confirm-modal recipe + V8 empty-state recipe
from cjm_fasthtml_app_core.components.confirm_modal import render_confirm_modal
from cjm_fasthtml_app_core.components.empty_state import render_empty_state

# Virtual Collection
from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, ColumnDef, CellRenderContext,
    VirtualCollectionUrls,
)
from cjm_fasthtml_virtual_collection.core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.button_ids import VirtualCollectionButtonIds
from cjm_fasthtml_virtual_collection.components.collection import render_virtual_collection

# Keyboard Navigation
from cjm_fasthtml_keyboard_navigation.components.system import render_keyboard_system
from cjm_fasthtml_keyboard_navigation.core.manager import ZoneManager
from cjm_fasthtml_virtual_collection.keyboard.actions import (
    create_collection_focus_zone,
    create_collection_nav_actions,
    build_collection_url_map,
    apply_nav_sync,
)

# JS generators
from cjm_fasthtml_virtual_collection.js.scroll import generate_scroll_nav_js
from cjm_fasthtml_virtual_collection.js.scrollbar import generate_scrollbar_js
from cjm_fasthtml_virtual_collection.js.auto_fit import generate_auto_fit_js, auto_fit_callback_name

# Viewport fit
from cjm_fasthtml_viewport_fit.models import ViewportFitConfig
from cjm_fasthtml_viewport_fit.components import render_viewport_fit_script

# Local imports
from ..models import DocumentSummary, ManagementUrls
from ..html_ids import ManagementHtmlIds
from ..utils import format_duration, format_date
from cjm_transcript_workflow_management.components.helpers import (
    render_icon_button, render_media_type_badge,
    DEBUG_MANAGEMENT_RENDER
)

# %% ../../nbs/components/document_list.ipynb #16eefe65
def build_document_columns() -> tuple:
    """Column definitions for the document list virtual collection."""
    return (
        ColumnDef(key="select", header="", sortable=False, header_cls=str(w("10"))),
        ColumnDef(key="title", header="Title", sortable=True),
        ColumnDef(key="type", header="Type", sortable=False),
        ColumnDef(key="segments", header="Segments", sortable=True),
        ColumnDef(key="duration", header="Duration", sortable=True),
        ColumnDef(key="created", header="Created", sortable=True),
        ColumnDef(key="actions", header="Actions", sortable=False),
    )

# %% ../../nbs/components/document_list.ipynb #1f742751
def create_document_cell_renderer(
    get_selected:Callable,  # () -> Set[str] of selected document IDs
    urls:'ManagementUrls',  # URL bundle for action buttons
    toggle_select_url:str="",  # URL for checkbox toggle route
) -> Callable:  # render_cell(item, ctx) -> FT component
    """Create a cell renderer for the document list virtual collection."""
    
    def render_cell(item, ctx):
        doc = item
        key = ctx.column.key
        
        if key == "select":
            checked = doc.document_id in get_selected()
            return Input(
                type="checkbox",
                cls=combine_classes(checkbox, checkbox_sizes.sm),
                checked=checked,
                hx_post=toggle_select_url,
                hx_vals=f'{{"doc_id": "{doc.document_id}"}}',
                hx_swap="none",
                onclick="event.stopPropagation()",
            )
        elif key == "title":
            return Span(doc.title, cls=str(font_weight.medium))
        elif key == "type":
            return render_media_type_badge(doc.media_type)
        elif key == "segments":
            return Span(f"{doc.segment_count} segs")
        elif key == "duration":
            return Span(format_duration(doc.total_duration))
        elif key == "created":
            return Span(format_date(doc.created_at), cls=str(font_size.sm))
        elif key == "actions":
            return Div(
                render_icon_button(
                    "eye", "View",
                    size=str(btn_sizes.sm),
                    hx_get=f"{urls.document_detail}?doc_id={doc.document_id}",
                    hx_target=f"#{ManagementHtmlIds.PAGE_CONTENT}",
                    hx_swap="innerHTML",
                ),
                A(
                    lucide_icon("download", size=icons.icon_button),
                    title="Export",
                    cls=combine_classes(btn, btn_styles.ghost, btn_sizes.sm),
                    href=f"{urls.export_document}?doc_id={doc.document_id}",
                    download=True,
                ),
                render_icon_button(
                    "trash-2", "Delete",
                    color=str(btn_colors.error),
                    size=str(btn_sizes.sm),
                    onclick=(
                        f"prepareDeleteModal('{doc.document_id}', '{doc.title}', {doc.segment_count}); "
                        f"document.getElementById('{ManagementHtmlIds.DELETE_MODAL}').showModal()"
                    ),
                ),
                cls=combine_classes(flex_display, gap(1)),
            )
        return Span("")
    
    return render_cell

# %% ../../nbs/components/document_list.ipynb #12fc0532
def render_toolbar(
    urls:ManagementUrls,  # URL bundle for route endpoints
    selected_count:int=0,  # Number of selected documents
    total_count:int=0,  # Total number of documents
    select_all_url:str="",  # URL for select-all toggle route
) -> Any:  # Toolbar element
    """Render the document list toolbar with Select All and bulk actions."""
    all_selected = selected_count == total_count and total_count > 0
    
    return Div(
        # Left side: Select All
        Label(
            Input(
                type="checkbox",
                cls=combine_classes(checkbox, checkbox_sizes.sm),
                id=ManagementHtmlIds.SELECT_ALL,
                checked=all_selected,
                hx_post=select_all_url,
                hx_swap="none",
            ),
            Span("Select All", cls=combine_classes(font_size.sm, m.l(2))),
            cls=combine_classes(flex_display, items.center),
        ),
        # Right side: Delete Selected
        Button(
            lucide_icon("trash-2", size=icons.text_button),
            f"Delete Selected ({selected_count})" if selected_count else "Delete Selected",
            cls=combine_classes(
                buttons.destructive_cancellable,
                flex_display, items.center, gap(1)
            ),
            id=ManagementHtmlIds.DELETE_SELECTED_BTN,
            disabled=selected_count == 0,
            onclick=f"prepareBulkDeleteModal(); document.getElementById('{ManagementHtmlIds.BULK_DELETE_MODAL}').showModal()",
        ),
        id=ManagementHtmlIds.TOOLBAR,
        cls=combine_classes(flex_display, justify.between, items.center, m.b(2)),
    )

# %% ../../nbs/components/document_list.ipynb #f361a3a2
def render_list_scripts(
    urls:ManagementUrls,  # URL bundle for route endpoints
) -> Any:  # Script element
    """Render client-side JavaScript for delete modal management."""
    return Script(f"""
    function prepareDeleteModal(docId, title, segCount) {{
        var body = document.getElementById('{ManagementHtmlIds.DELETE_MODAL_BODY}');
        if (body) {{
            body.innerHTML = '<p>Permanently delete "' + title + '" and all ' + segCount + ' segments?</p>'
                + '<p class="{combine_classes(font_size.sm, text_tiers.tertiary, m.t(2))}">This action cannot be undone.</p>';
        }}
        var confirmBtn = document.querySelector('#{ManagementHtmlIds.DELETE_MODAL} [data-delete-confirm]');
        if (confirmBtn) {{
            confirmBtn.setAttribute('hx-post', '{urls.delete_document}');
            confirmBtn.setAttribute('hx-vals', JSON.stringify({{doc_id: docId}}));
            confirmBtn.setAttribute('hx-swap', 'none');
            htmx.process(confirmBtn);
        }}
    }}

    function prepareBulkDeleteModal() {{
        var body = document.getElementById('{ManagementHtmlIds.BULK_DELETE_MODAL_BODY}');
        if (body) {{
            body.innerHTML = '<p>Permanently delete selected documents and all their segments?</p>'
                + '<p class="{combine_classes(font_size.sm, text_tiers.tertiary, m.t(2))}">This action cannot be undone.</p>';
        }}
    }}
    """)

# %% ../../nbs/components/document_list.ipynb #fdf58e55
def render_document_list(
    items:list,  # Current document list (List[DocumentSummary])
    selected:set,  # Selected document IDs (Set[str])
    vc_config:'VirtualCollectionConfig',  # VC configuration
    vc_state:'VirtualCollectionState',  # VC state
    vc_ids:'VirtualCollectionHtmlIds',  # VC HTML IDs
    vc_btn_ids:'VirtualCollectionButtonIds',  # VC button IDs
    vc_urls:'VirtualCollectionUrls',  # VC route URLs
    mgmt_urls:'ManagementUrls',  # Management URLs for actions
    render_cell:Callable,  # Cell renderer callback
    select_all_url:str="",  # URL for select-all toggle route
) -> Any:  # Complete document list component
    """Render the document list with virtual collection, keyboard nav, and modals."""
    if DEBUG_MANAGEMENT_RENDER:
        print(f"[RENDER] document_list: {len(items)} docs, {len(selected)} selected")
    
    # Empty state
    if not items:
        return Div(
            render_empty_state(
                message="No documents found.",
                detail="Complete a workflow to create a document, or import one.",
                icon_name="inbox",
            ),
            id=ManagementHtmlIds.DOCUMENT_LIST,
        )
    
    # Keyboard system — returns a dataclass, unpack individual components
    zone = create_collection_focus_zone(vc_ids)
    nav_actions = create_collection_nav_actions(zone.id, vc_btn_ids)
    manager = ZoneManager(zones=(zone,), actions=nav_actions)
    url_map = build_collection_url_map(vc_btn_ids, vc_urls)
    target_map = {btn_id: f"#{vc_ids.rows}" for btn_id in url_map}
    swap_map = {btn_id: "none" for btn_id in url_map}
    
    kb_system = render_keyboard_system(
        manager,
        url_map=url_map,
        target_map=target_map,
        swap_map=swap_map,
    )
    apply_nav_sync(kb_system, vc_ids)
    
    # Viewport fit for auto-sizing
    vf_config = ViewportFitConfig(
        namespace=vc_config.prefix,
        target_id=vc_ids.wrapper,
        resize_callback=auto_fit_callback_name(vc_config),
        enable_htmx_settle=False,
    )
    
    # JS scripts for VC navigation
    js_code = "\n".join([
        generate_scroll_nav_js(vc_ids, vc_btn_ids),
        generate_scrollbar_js(vc_ids, vc_urls),
        generate_auto_fit_js(vc_ids, vc_config, vc_urls, total_items=len(items)),
    ])
    
    return Div(
        # Toolbar
        render_toolbar(mgmt_urls, len(selected), len(items), select_all_url),
        # Virtual collection wrapped in flex container
        Div(
            render_virtual_collection(
                items=items,
                config=vc_config,
                state=vc_state,
                ids=vc_ids,
                urls=vc_urls,
                render_cell=render_cell,
                render_empty=lambda: render_empty_state(
                    message="No documents found.",
                    detail="Complete a workflow to create a document, or import one.",
                    icon_name="inbox",
                ),
            ),
            cls=combine_classes(
                flex_display, flex_direction.col, grow(1), min_h(0),
                overflow.hidden,
            ),
        ),
        # Alert area for feedback messages
        Div(id=ManagementHtmlIds.ALERT_AREA),
        # Single delete confirmation modal (V12 confirm-modal recipe)
        render_confirm_modal(
            modal_id=ManagementHtmlIds.DELETE_MODAL,
            body_id=ManagementHtmlIds.DELETE_MODAL_BODY,
            title="Delete Document?",
            confirm_label="Delete",
            confirm_icon="trash-2",
            confirm_attrs={
                "data_delete_confirm": "true",
                "onclick": f"document.getElementById('{ManagementHtmlIds.DELETE_MODAL}').close()",
            },
        ),
        # Bulk delete confirmation modal (V12 confirm-modal recipe; swap=none — response is all OOB)
        render_confirm_modal(
            modal_id=ManagementHtmlIds.BULK_DELETE_MODAL,
            body_id=ManagementHtmlIds.BULK_DELETE_MODAL_BODY,
            title="Delete Selected Documents?",
            confirm_label="Delete",
            confirm_icon="trash-2",
            confirm_attrs={
                "hx_post": mgmt_urls.delete_selected,
                "hx_swap": "none",
                "onclick": f"document.getElementById('{ManagementHtmlIds.BULK_DELETE_MODAL}').close()",
            },
        ),
        # Keyboard system components (unpacked from dataclass)
        kb_system.script,
        kb_system.hidden_inputs,
        kb_system.action_buttons,
        # Scripts
        render_list_scripts(mgmt_urls),
        Script(js_code),
        render_viewport_fit_script(vf_config),
        id=ManagementHtmlIds.DOCUMENT_LIST,
        cls=combine_classes(flex_display, flex_direction.col, grow(1), min_h(0)),
    )
