"""Shared rendering helpers for the management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = ['DEBUG_MANAGEMENT_RENDER', 'render_section_header', 'render_icon_button', 'render_media_type_badge', 'render_alert',
           'render_delete_modal', 'render_empty_state']

# %% ../../nbs/components/helpers.ipynb #68a88103
from typing import Any, Optional

from fasthtml.common import Div, Span, H3, Button, Form

# DaisyUI components
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_styles, btn_sizes
)
from cjm_fasthtml_daisyui.components.data_display.badge import (
    badge, badge_colors, badge_styles, badge_sizes
)
from cjm_fasthtml_daisyui.components.feedback.alert import alert, alert_colors
from cjm_fasthtml_daisyui.components.actions.modal import (
    modal, modal_box, modal_action
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight, text_align
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Debug flag
DEBUG_MANAGEMENT_RENDER = False

# %% ../../nbs/components/helpers.ipynb #8dc3b582
def render_section_header(
    title:str,  # Section title text
    icon_name:str,  # Lucide icon name (kebab-case)
) -> Any:  # Header element with icon and title
    """Render a section header with icon."""
    return H3(
        lucide_icon(icon_name, size=5),
        title,
        cls=combine_classes(
            font_size.lg, font_weight.semibold,
            flex_display, items.center, gap(2)
        )
    )

# %% ../../nbs/components/helpers.ipynb #9130f69b
def render_icon_button(
    icon_name:str,  # Lucide icon name (kebab-case)
    label:str,  # Accessible label text
    color:str=None,  # DaisyUI button color class (e.g., btn_colors.error)
    size:str=None,  # DaisyUI button size class (e.g., btn_sizes.sm)
    **kwargs  # Additional HTML attributes (onclick, hx_post, etc.)
) -> Any:  # Button element with icon
    """Render a button with an icon and accessible label."""
    classes = [btn, btn_styles.ghost]
    if color: classes.append(color)
    if size: classes.append(size)
    return Button(
        lucide_icon(icon_name, size=4),
        title=label,
        cls=combine_classes(*classes),
        **kwargs
    )

# %% ../../nbs/components/helpers.ipynb #b255a7c0
def render_media_type_badge(
    media_type:str,  # Media type string (e.g., "audio")
) -> Any:  # Badge element
    """Render a badge for media type display."""
    return Span(
        media_type,
        cls=combine_classes(badge, badge_styles.outline, badge_sizes.sm)
    )

# %% ../../nbs/components/helpers.ipynb #6d37fd3e
def render_alert(
    message:str,  # Alert message text
    color:str=None,  # DaisyUI alert color class (e.g., alert_colors.success)
    alert_id:str="",  # Optional HTML ID for the alert
) -> Any:  # Alert element
    """Render a DaisyUI alert message."""
    classes = [alert]
    if color: classes.append(color)
    kwargs = {"role": "alert", "cls": combine_classes(*classes)}
    if alert_id: kwargs["id"] = alert_id
    return Div(Span(message), **kwargs)

# %% ../../nbs/components/helpers.ipynb #8ea6d7e5
def render_delete_modal(
    modal_id:str,  # HTML ID for the dialog element
    body_id:str,  # HTML ID for the modal body (for HTMX swaps)
    title:str="Delete Document?",  # Modal title text
    confirm_attrs:dict=None,  # Attributes for the confirm button (hx_delete, etc.)
) -> Any:  # Dialog element
    """Render a delete confirmation modal using HTML5 dialog."""
    from fasthtml.common import Dialog, P
    
    confirm_attrs = confirm_attrs or {}
    
    return Dialog(
        Div(
            H3(title, cls=combine_classes(font_size.lg, font_weight.bold)),
            Div(id=body_id, cls=m.y(4)),
            Div(
                Form(
                    Button("Cancel", cls=str(btn), formmethod="dialog"),
                    method="dialog"
                ),
                Button(
                    lucide_icon("trash-2", size=4),
                    "Delete",
                    cls=combine_classes(
                        btn, btn_colors.error,
                        flex_display, items.center, gap(1)
                    ),
                    **confirm_attrs
                ),
                cls=combine_classes(modal_action, flex_display, gap(2))
            ),
            cls=str(modal_box)
        ),
        id=modal_id,
        cls=str(modal)
    )

# %% ../../nbs/components/helpers.ipynb #29a6519b
def render_empty_state(
    message:str="No documents found.",  # Primary message
    detail:str="Complete a workflow to create a document, or import one.",  # Secondary detail
) -> Any:  # Empty state element
    """Render an empty state placeholder."""
    from fasthtml.common import P
    return Div(
        lucide_icon("inbox", size=12, cls=str(text_dui.base_content.opacity(30))),
        P(message, cls=combine_classes(
            font_size.lg, font_weight.medium, m.t(4)
        )),
        P(detail, cls=combine_classes(
            font_size.sm, text_dui.base_content.opacity(60)
        )),
        cls=combine_classes(
            flex_display, flex_direction.col, items.center, justify.center,
            text_align.center, p(12)
        )
    )
