"""Shared rendering helpers for the management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = ['DEBUG_MANAGEMENT_RENDER', 'render_section_header', 'render_icon_button', 'render_media_type_badge', 'render_alert',
           'render_empty_state']

# %% ../../nbs/components/helpers.ipynb #06c1e20e
from typing import Any, Optional

from fasthtml.common import Div, Span, H3, Button

# DaisyUI components
# btn / btn_styles / btn_colors / btn_sizes still used by `render_icon_button`
# (a row-action helper that pre-dates V1 and represents a V1 catalog gap for
# row-action icon buttons). Other sites in this file use V1 buttons directly.
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_styles, btn_sizes
)
from cjm_fasthtml_daisyui.components.data_display.badge import (
    badge, badge_colors, badge_styles, badge_sizes
)
from cjm_fasthtml_daisyui.components.feedback.alert import alert, alert_colors
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight, text_align
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V1 button roles, V11 icon-size roles)
from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons

# Debug flag
DEBUG_MANAGEMENT_RENDER = False

# %% ../../nbs/components/helpers.ipynb #9bf66e39
def render_section_header(
    title:str,  # Section title text
    icon_name:str,  # Lucide icon name (kebab-case)
) -> Any:  # Header element with icon and title
    """Render a section header with icon."""
    return H3(
        lucide_icon(icon_name, size=icons.section_header),
        title,
        cls=combine_classes(
            font_size.lg, font_weight.semibold,
            flex_display, items.center, gap(2)
        )
    )

# %% ../../nbs/components/helpers.ipynb #59d3f8ce
def render_icon_button(
    icon_name:str,  # Lucide icon name (kebab-case)
    label:str,  # Accessible label text
    color:str=None,  # DaisyUI button color class (e.g., btn_colors.error)
    size:str=None,  # DaisyUI button size class (e.g., btn_sizes.sm)
    **kwargs  # Additional HTML attributes (onclick, hx_post, etc.)
) -> Any:  # Button element with icon
    """Render a button with an icon and accessible label."""
    classes = [btn, btn_styles.ghost]
    if color: classes.append(color)
    if size: classes.append(size)
    return Button(
        lucide_icon(icon_name, size=icons.icon_button),
        title=label,
        cls=combine_classes(*classes),
        **kwargs
    )

# %% ../../nbs/components/helpers.ipynb #9bf7992d
def render_media_type_badge(
    media_type:str,  # Media type string (e.g., "audio")
) -> Any:  # Badge element
    """Render a badge for media type display."""
    return Span(
        media_type,
        cls=combine_classes(badge, badge_styles.outline, badge_sizes.sm)
    )

# %% ../../nbs/components/helpers.ipynb #3c80ecfb
def render_alert(
    message:str,  # Alert message text
    color:str=None,  # DaisyUI alert color class (e.g., alert_colors.success)
    alert_id:str="",  # Optional HTML ID for the alert
) -> Any:  # Alert element
    """Render a DaisyUI alert message."""
    classes = [alert]
    if color: classes.append(color)
    kwargs = {"role": "alert", "cls": combine_classes(*classes)}
    if alert_id: kwargs["id"] = alert_id
    return Div(Span(message), **kwargs)

# %% ../../nbs/components/helpers.ipynb #fc639019
def render_empty_state(
    message:str="No documents found.",  # Primary message
    detail:str="Complete a workflow to create a document, or import one.",  # Secondary detail
) -> Any:  # Empty state element
    """Render an empty state placeholder."""
    from fasthtml.common import P
    return Div(
        lucide_icon("inbox", size=icons.empty_state, cls=str(text_dui.base_content.opacity(30))),
        P(message, cls=combine_classes(
            font_size.lg, font_weight.medium, m.t(4)
        )),
        P(detail, cls=combine_classes(
            font_size.sm, text_dui.base_content.opacity(60)
        )),
        cls=combine_classes(
            flex_display, flex_direction.col, items.center, justify.center,
            text_align.center, p(12)
        )
    )
