"""Main management page renderer composing header, toolbar buttons, and document list"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/page_renderer.ipynb.

# %% auto #0
__all__ = ['render_page_header', 'render_management_page']

# %% ../../nbs/components/page_renderer.ipynb #e8a9256c
from typing import Any, List

from fasthtml.common import Div, H1, Span, Button

# DaisyUI components
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_styles, btn_sizes
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import container, max_w
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Local imports
from ..models import DocumentSummary, ManagementUrls
from ..html_ids import ManagementHtmlIds
from .document_list import render_document_list
from .helpers import DEBUG_MANAGEMENT_RENDER

# %% ../../nbs/components/page_renderer.ipynb #1add562a
def render_page_header(
    urls:ManagementUrls,  # URL bundle for route endpoints
) -> Any:  # Header element with title and action buttons
    """Render the management page header with title and top-level actions."""
    return Div(
        # Title
        H1(
            lucide_icon("database", size=7),
            "Graph Management",
            cls=combine_classes(
                font_size._3xl, font_weight.bold,
                flex_display, items.center, gap(3)
            )
        ),
        # Action buttons
        Div(
            Button(
                lucide_icon("upload", size=4),
                "Import",
                cls=combine_classes(
                    btn, btn_styles.outline, btn_sizes.sm,
                    flex_display, items.center, gap(1)
                ),
                disabled=True,
                title="Import (coming in Phase 5)",
            ),
            Button(
                lucide_icon("download", size=4),
                "Export All",
                cls=combine_classes(
                    btn, btn_styles.outline, btn_sizes.sm,
                    flex_display, items.center, gap(1)
                ),
                disabled=True,
                title="Export All (coming in Phase 5)",
            ),
            cls=combine_classes(flex_display, gap(2)),
        ),
        cls=combine_classes(flex_display, justify.between, items.center, m.b(6)),
    )

# %% ../../nbs/components/page_renderer.ipynb #62fd2de3
def render_management_page(
    documents:List[DocumentSummary],  # List of document summaries
    urls:ManagementUrls,  # URL bundle for route endpoints
) -> Any:  # Complete management page component
    """Render the complete management page with header and document list."""
    if DEBUG_MANAGEMENT_RENDER:
        print(f"[RENDER] management_page: {len(documents)} docs")
    
    return Div(
        render_page_header(urls),
        render_document_list(documents, urls),
        id=ManagementHtmlIds.PAGE_CONTENT,
        cls=combine_classes(
            container, max_w._5xl, m.x.auto,
            flex_display, flex_direction.col,
            p(4), gap(4)
        )
    )
