"""HTML ID constants for the graph management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['ManagementHtmlIds']

# %% ../nbs/html_ids.ipynb #c1d2e3f4
# Framework-agnostic — no external imports needed

class ManagementHtmlIds:
    """HTML ID constants for the graph management interface."""

    @staticmethod
    def as_selector(
        id_str: str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Page sections
    PAGE_CONTENT = "mgmt-page-content"
    DOCUMENT_LIST = "mgmt-document-list"
    DOCUMENT_DETAIL = "mgmt-document-detail"

    # Toolbar
    TOOLBAR = "mgmt-toolbar"
    SELECT_ALL = "mgmt-select-all"
    DELETE_SELECTED_BTN = "mgmt-delete-selected-btn"

    # Modals
    DELETE_MODAL = "mgmt-delete-modal"
    DELETE_MODAL_BODY = "mgmt-delete-modal-body"
    BULK_DELETE_MODAL = "mgmt-bulk-delete-modal"
    BULK_DELETE_MODAL_BODY = "mgmt-bulk-delete-modal-body"

    # Import
    IMPORT_SECTION = "mgmt-import-section"
    IMPORT_RESULT = "mgmt-import-result"

    # Feedback
    ALERT_AREA = "mgmt-alert-area"
