"""Data models for the graph management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SegmentSample', 'DocumentSummary', 'DocumentDetail', 'ExportBundle', 'ImportResult', 'ManagementUrls',
           'ManagementResult']

# %% ../nbs/models.ipynb #d1e2f3a4
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

# %% ../nbs/models.ipynb #f1a2b3c4
@dataclass
class SegmentSample:
    """Lightweight segment snapshot for detail view display."""
    index: int          # Segment position in the document
    text: str           # Segment text content
    start_time: float   # Start time in seconds
    end_time: float     # End time in seconds

# %% ../nbs/models.ipynb #c2d3e4f5
@dataclass
class DocumentSummary:
    """Summary of a single document for list display."""
    document_id: str        # Document node UUID
    title: str              # Document title from properties
    media_type: str         # e.g. "audio"
    segment_count: int      # Number of Segment nodes
    total_duration: float   # Sum of segment durations in seconds
    created_at: float       # Unix timestamp when created

# %% ../nbs/models.ipynb #f2a3b4c5
@dataclass
class DocumentDetail:
    """Full document information for the detail dashboard."""
    # Document info
    document_id: str        # Document node UUID
    title: str              # Document title
    media_type: str         # e.g. "audio"
    created_at: float       # Unix timestamp
    updated_at: float       # Unix timestamp

    # Segment stats
    segment_count: int              # Total number of segments
    total_duration: float           # Sum of segment durations in seconds
    avg_segment_duration: float     # Average segment duration in seconds

    # Integrity checks
    has_starts_with: bool           # Document has a STARTS_WITH edge
    next_chain_complete: bool       # All NEXT edges form a complete chain
    next_count: int                 # Number of NEXT edges found
    part_of_complete: bool          # All segments have PART_OF edges
    part_of_count: int              # Number of PART_OF edges found
    all_have_timing: bool           # All segments have start_time/end_time
    segments_missing_timing: int    # Count of segments without timing
    all_have_sources: bool          # All segments have source references
    segments_missing_sources: int   # Count of segments without sources
    all_checks_passed: bool         # True if all integrity checks pass

    # Source info
    source_plugins: List[str] = field(default_factory=list)  # Unique plugin names from sources

    # Sample segments
    first_segments: List[SegmentSample] = field(default_factory=list)  # First N segments
    last_segments: List[SegmentSample] = field(default_factory=list)   # Last N segments

# %% ../nbs/models.ipynb #c3d4e5f6
@dataclass
class ExportBundle:
    """Metadata wrapper for exported graph data."""
    format: str              # Always "cjm-context-graph"
    version: str             # Semantic version, e.g. "1.0.0"
    exported_at: str         # ISO 8601 datetime string
    source_plugin: str       # Plugin that produced the data
    document_count: int      # Number of Document nodes in the export
    graph: Dict[str, Any]    # {"nodes": [...], "edges": [...]}

# %% ../nbs/models.ipynb #f3a4b5c6
@dataclass
class ImportResult:
    """Result of a graph import operation."""
    success: bool           # Whether the import succeeded
    nodes_created: int      # Number of nodes created
    edges_created: int      # Number of edges created
    nodes_skipped: int      # Number of nodes skipped (already exist)
    edges_skipped: int      # Number of edges skipped (already exist)
    errors: List[str] = field(default_factory=list)  # Error messages if any

# %% ../nbs/models.ipynb #c4d5e6f7
@dataclass
class ManagementUrls:
    """URL bundle for management route endpoints."""
    management_page: str    # GET: full page (header + import + list)
    list_documents: str     # GET: document list only
    document_detail: str    # GET: + ?doc_id=...
    delete_document: str    # POST: + doc_id in form data
    delete_selected: str    # POST: bulk delete
    export_document: str    # GET: + ?doc_id=...
    export_all: str         # GET: full database export
    import_graph: str       # POST: file upload import

# %% ../nbs/models.ipynb #07itdh2zky04
@dataclass
class ManagementResult:
    """Result of management router initialization."""
    routers: List[Any]          # APIRouter instances to register
    urls: ManagementUrls        # URL bundle for route endpoints
    routes: Dict[str, Callable] # Route handler functions
    render_page: Callable       # () -> full management page component
    render_list: Callable       # () -> document list component
    refresh_items: Callable     # async () -> refresh items from service
