"""Formatting utilities for the management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['format_duration', 'format_duration_short', 'format_date', 'format_datetime', 'truncate_text', 'format_time_range']

# %% ../nbs/utils.ipynb #d1e2f3a4
from datetime import datetime, timezone
from typing import Optional

# %% ../nbs/utils.ipynb #f1a2b3c4
def format_duration(
    seconds: Optional[float]  # Duration in seconds
) -> str:  # Formatted string (MM:SS or H:MM:SS)
    """Format duration for display in document list and detail views."""
    if seconds is None or seconds < 0:
        return "--:--"
    total_secs = int(seconds)
    hours = total_secs // 3600
    minutes = (total_secs % 3600) // 60
    secs = total_secs % 60
    if hours > 0:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"

# %% ../nbs/utils.ipynb #b2c3d4e5
def format_duration_short(
    seconds: Optional[float]  # Duration in seconds
) -> str:  # Formatted string (e.g., "10.3s")
    """Format duration as compact seconds for average display."""
    if seconds is None:
        return "-.-s"
    return f"{seconds:.1f}s"

# %% ../nbs/utils.ipynb #e2f3a4b5
def format_date(
    timestamp: Optional[float]  # Unix timestamp
) -> str:  # Formatted date string (e.g., "Feb 19, 2026")
    """Format unix timestamp as a human-readable date."""
    if timestamp is None:
        return "—"
    dt = datetime.fromtimestamp(timestamp, tz=timezone.utc)
    return dt.strftime("%b %d, %Y")

# %% ../nbs/utils.ipynb #a3b4c5d6
def format_datetime(
    timestamp: Optional[float]  # Unix timestamp
) -> str:  # Formatted datetime string (e.g., "Feb 19, 2026 12:00")
    """Format unix timestamp as a human-readable date and time."""
    if timestamp is None:
        return "—"
    dt = datetime.fromtimestamp(timestamp, tz=timezone.utc)
    return dt.strftime("%b %d, %Y %H:%M")

# %% ../nbs/utils.ipynb #d3e4f5a6
def truncate_text(
    text: Optional[str],  # Full text to truncate
    max_length: int = 60  # Maximum length before truncation
) -> str:  # Truncated text with ellipsis if needed
    """Truncate text for table and sample display."""
    if text is None:
        return ""
    if len(text) <= max_length:
        return text
    return f"{text[:max_length-3]}..."

# %% ../nbs/utils.ipynb #f3a4b5c6
def format_time_range(
    start: Optional[float],  # Start time in seconds
    end: Optional[float]     # End time in seconds
) -> str:  # Formatted range (e.g., "0.0s - 2.1s")
    """Format a time range for sample segment display."""
    if start is None or end is None:
        return "-.-s - -.-s"
    return f"{start:.1f}s - {end:.1f}s"
