"""Request helpers for management routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/core.ipynb.

# %% auto #0
__all__ = ['DEBUG_MANAGEMENT_ROUTES']

# %% ../../nbs/routes/core.ipynb #c5978900
from ..services.management import ManagementService

# Debug flag for route tracing
DEBUG_MANAGEMENT_ROUTES = False
