"""Document list, detail, and delete routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/documents.ipynb.

# %% auto #0
__all__ = ['init_document_router']

# %% ../../nbs/routes/documents.ipynb #764b2783
from typing import Dict, Callable, Tuple

from fasthtml.common import APIRouter, Div, P

from ..services.management import ManagementService
from ..models import ManagementUrls
from ..components.document_list import render_document_list
from ..components.helpers import render_alert
from ..html_ids import ManagementHtmlIds
from .core import DEBUG_MANAGEMENT_ROUTES

from cjm_fasthtml_daisyui.components.feedback.alert import alert_colors

# %% ../../nbs/routes/documents.ipynb #eba8fa7c
def init_document_router(
    service:ManagementService,  # Service for graph queries
    prefix:str,  # Route prefix (e.g., "/manage/documents")
    urls:ManagementUrls,  # URL bundle (populated after init)
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, routes dict)
    """Initialize document list, detail, and delete routes."""
    router = APIRouter(prefix=prefix)
    routes = {}
    
    @router
    async def list_documents(request):
        """Return rendered document list."""
        if DEBUG_MANAGEMENT_ROUTES:
            print("[ROUTES] list_documents called")
        
        documents = await service.list_documents_async()
        
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] Found {len(documents)} documents")
        
        return render_document_list(documents, urls)
    
    routes["list_documents"] = list_documents
    
    @router
    async def document_detail(request, doc_id:str):
        """Return document detail view (placeholder for Phase 4)."""
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] document_detail called for {doc_id}")
        
        return Div(
            P(f"Document detail for {doc_id[:12]}... (coming in Phase 4)"),
            id=ManagementHtmlIds.DOCUMENT_DETAIL,
        )
    
    routes["document_detail"] = document_detail
    
    @router.post
    async def delete_document(request):
        """Delete a single document and return refreshed list."""
        form_data = await request.form()
        doc_id = form_data.get("doc_id", "")
        
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] delete_document called for {doc_id}")
        
        if doc_id:
            success = await service.delete_document_async(doc_id)
            if DEBUG_MANAGEMENT_ROUTES:
                print(f"[ROUTES] Delete result: {success}")
        
        # Refresh the document list
        documents = await service.list_documents_async()
        return render_document_list(documents, urls)
    
    routes["delete_document"] = delete_document
    
    @router.post
    async def delete_selected(request):
        """Delete multiple selected documents and return refreshed list."""
        form_data = await request.form()
        doc_ids = form_data.getlist("doc_ids")
        
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] delete_selected called for {len(doc_ids)} docs")
        
        if doc_ids:
            deleted_count = await service.delete_documents_async(doc_ids)
            if DEBUG_MANAGEMENT_ROUTES:
                print(f"[ROUTES] Deleted {deleted_count} documents")
        
        # Refresh the document list
        documents = await service.list_documents_async()
        return render_document_list(documents, urls)
    
    routes["delete_selected"] = delete_selected
    
    return router, routes
