"""Import route for file upload with JSON validation and merge strategy"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/import_.ipynb.

# %% auto #0
__all__ = ['init_import_router']

# %% ../../nbs/routes/import_.ipynb #c1d2e3f4
import json
from typing import Callable, Dict, Tuple

from fasthtml.common import APIRouter, UploadFile, Div

from ..services.management import ManagementService
from ..models import ManagementUrls, ImportResult
from ..html_ids import ManagementHtmlIds
from ..components.import_controls import render_import_result
from .core import DEBUG_MANAGEMENT_ROUTES

# %% ../../nbs/routes/import_.ipynb #e1f2a3b4
def init_import_router(
    service:ManagementService,  # Service for graph queries
    prefix:str,  # Route prefix (e.g., "/manage/import")
    urls:ManagementUrls,  # URL bundle (for list refresh)
    refresh_items_oob:Callable,  # async () -> refresh + targeted VC OOB tuple
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, routes dict)
    """Initialize import route for file upload with merge strategy."""
    router = APIRouter(prefix=prefix)
    routes = {}
    
    @router.post
    async def import_graph(file:UploadFile, merge_strategy:str="skip"):
        """Import a graph from an uploaded JSON file."""
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] import_graph called, strategy={merge_strategy}")
        
        # Validate file was provided
        if file is None or not file.filename:
            result = ImportResult(
                success=False, nodes_created=0, edges_created=0,
                nodes_skipped=0, edges_skipped=0,
                errors=["No file provided"],
            )
            return render_import_result(result)
        
        # Read and parse JSON
        try:
            content = await file.read()
            bundle_data = json.loads(content)
        except json.JSONDecodeError as e:
            result = ImportResult(
                success=False, nodes_created=0, edges_created=0,
                nodes_skipped=0, edges_skipped=0,
                errors=[f"Invalid JSON: {e}"],
            )
            return render_import_result(result)
        except Exception as e:
            result = ImportResult(
                success=False, nodes_created=0, edges_created=0,
                nodes_skipped=0, edges_skipped=0,
                errors=[f"Error reading file: {e}"],
            )
            return render_import_result(result)
        
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] Parsed JSON, format={bundle_data.get('format')}, "
                  f"version={bundle_data.get('version')}")
        
        # Import via service
        result = await service.import_graph_async(bundle_data, merge_strategy)
        
        if DEBUG_MANAGEMENT_ROUTES:
            print(f"[ROUTES] Import result: success={result.success}, "
                  f"nodes={result.nodes_created}, edges={result.edges_created}")
        
        # Return result alert + targeted VC OOB refresh
        vc_oobs = await refresh_items_oob()
        return (render_import_result(result), *vc_oobs)
    
    routes["import_graph"] = import_graph
    
    return router, routes
