"""Router assembly for management routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/init.ipynb.

# %% auto #0
__all__ = ['init_management_routers']

# %% ../../nbs/routes/init.ipynb #d83e89a2
from typing import List, Dict, Callable, Tuple

from fasthtml.common import APIRouter

from ..models import ManagementUrls
from ..services.management import ManagementService
from .documents import init_document_router

# %% ../../nbs/routes/init.ipynb #49fc88fe
def init_management_routers(
    service:ManagementService,  # Service for graph queries
    prefix:str,  # Base prefix for management routes (e.g., "/manage")
) -> Tuple[List[APIRouter], ManagementUrls, Dict[str, Callable]]:  # (routers, urls, routes)
    """Initialize and return all management routers with URL bundle."""
    # Create empty URL bundle (populated after routes are defined)
    urls = ManagementUrls(
        list_documents="",
        document_detail="",
        delete_document="",
        delete_selected="",
        export_document="",
        export_all="",
        import_graph="",
    )
    
    # Initialize document router
    doc_router, doc_routes = init_document_router(
        service, f"{prefix}/documents", urls
    )
    
    # Populate URL bundle using .to() on route functions
    urls.list_documents = doc_routes["list_documents"].to()
    urls.document_detail = doc_routes["document_detail"].to()
    urls.delete_document = doc_routes["delete_document"].to()
    urls.delete_selected = doc_routes["delete_selected"].to()
    
    # Export/import URLs will be populated in Phase 5
    urls.export_document = f"{prefix}/export/document"
    urls.export_all = f"{prefix}/export/all"
    urls.import_graph = f"{prefix}/import"
    
    routers = [doc_router]
    all_routes = {**doc_routes}
    
    return routers, urls, all_routes
